[2025-07-29T07:57:07.073+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-29T07:57:09.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T07:53:35.889550+00:00 map_index=0 [queued]>
[2025-07-29T07:57:10.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T07:53:35.889550+00:00 map_index=0 [queued]>
[2025-07-29T07:57:10.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-29T07:57:20.109+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): scrape_task> on 2025-07-29 07:53:35.889550+00:00
[2025-07-29T07:57:20.164+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2842) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-29T07:57:20.163+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_scraping_pipeline', 'scrape_task', 'manual__2025-07-29T07:53:35.889550+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/parallel_pipeline_dag.py', '--cfg-path', '/tmp/tmpnui26e5m', '--map-index', '0']
[2025-07-29T07:57:20.168+0000] {standard_task_runner.py:64} INFO - Started process 2875 to run task
[2025-07-29T07:57:20.168+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask scrape_task
[2025-07-29T07:57:23.879+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-29T07:57:33.163+0000] {task_command.py:426} INFO - Running <TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T07:53:35.889550+00:00 map_index=0 [running]> on host 507e5441ba68
[2025-07-29T07:58:26.541+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2619, in _execute_task_with_callbacks
    self.clear_xcom_data()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1860, in clear_xcom_data
    self._clear_xcom_data(ti=self, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1850, in _clear_xcom_data
    XCom.clear(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 652, in clear
    for xcom in query:
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2901, in __iter__
    result = self._iter()
             ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

[SQL: SELECT xcom.dag_run_id AS xcom_dag_run_id, xcom.task_id AS xcom_task_id, xcom.map_index AS xcom_map_index, xcom.key AS xcom_key, xcom.dag_id AS xcom_dag_id, xcom.run_id AS xcom_run_id, xcom.value AS xcom_value, xcom.timestamp AS xcom_timestamp, dag_run_1.state AS dag_run_1_state, dag_run_1.id AS dag_run_1_id, dag_run_1.dag_id AS dag_run_1_dag_id, dag_run_1.queued_at AS dag_run_1_queued_at, dag_run_1.execution_date AS dag_run_1_execution_date, dag_run_1.start_date AS dag_run_1_start_date, dag_run_1.end_date AS dag_run_1_end_date, dag_run_1.run_id AS dag_run_1_run_id, dag_run_1.creating_job_id AS dag_run_1_creating_job_id, dag_run_1.external_trigger AS dag_run_1_external_trigger, dag_run_1.run_type AS dag_run_1_run_type, dag_run_1.conf AS dag_run_1_conf, dag_run_1.data_interval_start AS dag_run_1_data_interval_start, dag_run_1.data_interval_end AS dag_run_1_data_interval_end, dag_run_1.last_scheduling_decision AS dag_run_1_last_scheduling_decision, dag_run_1.dag_hash AS dag_run_1_dag_hash, dag_run_1.log_template_id AS dag_run_1_log_template_id, dag_run_1.updated_at AS dag_run_1_updated_at, dag_run_1.clear_number AS dag_run_1_clear_number 
FROM xcom LEFT OUTER JOIN dag_run AS dag_run_1 ON xcom.dag_run_id = dag_run_1.id 
WHERE xcom.dag_id = %(dag_id_1)s AND xcom.task_id = %(task_id_1)s AND xcom.run_id = %(run_id_1)s AND xcom.map_index = %(map_index_1)s]
[parameters: {'dag_id_1': 'parallel_scraping_pipeline', 'task_id_1': 'scrape_task', 'run_id_1': 'manual__2025-07-29T07:53:35.889550+00:00', 'map_index_1': 0}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-29T07:58:49.043+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parallel_scraping_pipeline, task_id=scrape_task, run_id=manual__2025-07-29T07:53:35.889550+00:00, map_index=0, execution_date=20250729T075335, start_date=20250729T075709, end_date=20250729T075844
[2025-07-29T07:59:05.527+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task scrape_task ((psycopg2.OperationalError) SSL SYSCALL error: EOF detected

[SQL: SELECT xcom.dag_run_id AS xcom_dag_run_id, xcom.task_id AS xcom_task_id, xcom.map_index AS xcom_map_index, xcom.key AS xcom_key, xcom.dag_id AS xcom_dag_id, xcom.run_id AS xcom_run_id, xcom.value AS xcom_value, xcom.timestamp AS xcom_timestamp, dag_run_1.state AS dag_run_1_state, dag_run_1.id AS dag_run_1_id, dag_run_1.dag_id AS dag_run_1_dag_id, dag_run_1.queued_at AS dag_run_1_queued_at, dag_run_1.execution_date AS dag_run_1_execution_date, dag_run_1.start_date AS dag_run_1_start_date, dag_run_1.end_date AS dag_run_1_end_date, dag_run_1.run_id AS dag_run_1_run_id, dag_run_1.creating_job_id AS dag_run_1_creating_job_id, dag_run_1.external_trigger AS dag_run_1_external_trigger, dag_run_1.run_type AS dag_run_1_run_type, dag_run_1.conf AS dag_run_1_conf, dag_run_1.data_interval_start AS dag_run_1_data_interval_start, dag_run_1.data_interval_end AS dag_run_1_data_interval_end, dag_run_1.last_scheduling_decision AS dag_run_1_last_scheduling_decision, dag_run_1.dag_hash AS dag_run_1_dag_hash, dag_run_1.log_template_id AS dag_run_1_log_template_id, dag_run_1.updated_at AS dag_run_1_updated_at, dag_run_1.clear_number AS dag_run_1_clear_number 
FROM xcom LEFT OUTER JOIN dag_run AS dag_run_1 ON xcom.dag_run_id = dag_run_1.id 
WHERE xcom.dag_id = %(dag_id_1)s AND xcom.task_id = %(task_id_1)s AND xcom.run_id = %(run_id_1)s AND xcom.map_index = %(map_index_1)s]
[parameters: {'dag_id_1': 'parallel_scraping_pipeline', 'task_id_1': 'scrape_task', 'run_id_1': 'manual__2025-07-29T07:53:35.889550+00:00', 'map_index_1': 0}]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 2875)
[2025-07-29T07:59:06.271+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-29T07:59:16.878+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
