[2025-07-27T09:54:57.370+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T09:54:57.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.clean_task manual__2025-07-27T08:42:32.706579+00:00 map_index=1 [queued]>
[2025-07-27T09:54:57.544+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.clean_task manual__2025-07-27T08:42:32.706579+00:00 map_index=1 [queued]>
[2025-07-27T09:54:57.545+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-27T09:54:57.578+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): clean_task> on 2025-07-27 08:42:32.706579+00:00
[2025-07-27T09:54:57.599+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=70484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T09:54:57.601+0000] {standard_task_runner.py:64} INFO - Started process 70518 to run task
[2025-07-27T09:54:57.599+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parallel_scraping_pipeline', 'clean_task', 'manual__2025-07-27T08:42:32.706579+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/parallel_pipeline_dag.py', '--cfg-path', '/tmp/tmphzydkikg', '--map-index', '1']
[2025-07-27T09:54:57.603+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask clean_task
[2025-07-27T09:54:57.634+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T09:54:57.768+0000] {task_command.py:426} INFO - Running <TaskInstance: parallel_scraping_pipeline.clean_task manual__2025-07-27T08:42:32.706579+00:00 map_index=1 [running]> on host c5e8c6942178
[2025-07-27T09:54:57.965+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parallel_scraping_pipeline' AIRFLOW_CTX_TASK_ID='clean_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T08:42:32.706579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-27T08:42:32.706579+00:00'
[2025-07-27T09:54:57.968+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T09:54:57.993+0000] {logging_mixin.py:188} INFO - Processing 100 reviews from vivo_T4_Lite_5G_Charger_in_the_Box_(Titanium_Gold,_128_GB)__(4_GB_RAM)_reviews.csv...
[2025-07-27T09:54:58.001+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T09:54:58.002+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parallel_pipeline_dag.py", line 34, in clean_task
    return clean_raw_review_data(csv_path=raw_file_path, output_folder=CLEANED_DATA_FOLDER)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/cleaning.py", line 25, in clean_raw_review_data
    df['Price'] = df['Price'].astype(str).str.replace(r'[â‚¹,]', '', regex=True).str.extract(r'(\d+)').astype(float, errors='coerce')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 223, in astype_array_safe
    raise ValueError(invalid_arg)
ValueError: Expected value of kwarg 'errors' to be one of ['raise', 'ignore']. Supplied value is 'coerce'
[2025-07-27T09:54:58.047+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parallel_scraping_pipeline, task_id=clean_task, run_id=manual__2025-07-27T08:42:32.706579+00:00, map_index=1, execution_date=20250727T084232, start_date=20250727T095457, end_date=20250727T095458
[2025-07-27T09:54:58.065+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task clean_task (Expected value of kwarg 'errors' to be one of ['raise', 'ignore']. Supplied value is 'coerce'; 70518)
[2025-07-27T09:54:58.105+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-27T09:54:58.147+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-27T09:54:58.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
