[2025-07-25T09:54:25.197+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T09:54:25.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T09:54:15.883996+00:00 [queued]>
[2025-07-25T09:54:25.326+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T09:54:15.883996+00:00 [queued]>
[2025-07-25T09:54:25.332+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-25T09:54:25.386+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): scrape_task> on 2025-07-25 09:54:15.883996+00:00
[2025-07-25T09:54:25.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3579) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-25T09:54:25.416+0000] {standard_task_runner.py:64} INFO - Started process 3589 to run task
[2025-07-25T09:54:25.415+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flipkart_sentiment_pipeline_v2', 'scrape_task', 'manual__2025-07-25T09:54:15.883996+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/sentiment_pipeline_dag.py', '--cfg-path', '/tmp/tmpgstd6z9g']
[2025-07-25T09:54:25.418+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask scrape_task
[2025-07-25T09:54:25.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-07-25T09:54:25.616+0000] {task_command.py:426} INFO - Running <TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T09:54:15.883996+00:00 [running]> on host 9435d83f948a
[2025-07-25T09:54:25.936+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flipkart_sentiment_pipeline_v2' AIRFLOW_CTX_TASK_ID='scrape_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T09:54:15.883996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T09:54:15.883996+00:00'
[2025-07-25T09:54:25.946+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T09:54:25.952+0000] {logging_mixin.py:188} INFO - Starting scrape for URL: https://www.flipkart.com/apple-iphone-15-black-128-gb/p/itme5f540d559560
[2025-07-25T09:54:25.957+0000] {logging_mixin.py:188} INFO - Initializing WebDriver...
[2025-07-25T09:54:25.959+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-07-25T09:54:26.061+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T09:54:26.981+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-07-25T09:54:27.365+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-07-25T09:55:23.962+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T09:55:24.613+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T09:55:24.935+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-07-25T09:55:25.979+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T09:55:25.980+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sentiment_pipeline_dag.py", line 39, in scrape_task
    file_path = scrape_reviews_for_url(phone_url=url, output_folder=RAW_DATA_FOLDER)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraper_module.py", line 55, in scrape_reviews_for_url
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 261, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 362, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5e9dfdc4f4e3 <unknown>
#1 0x5e9dfd97ec76 <unknown>
#2 0x5e9dfd9a7d78 <unknown>
#3 0x5e9dfd9a4029 <unknown>
#4 0x5e9dfd9e2ccc <unknown>
#5 0x5e9dfd9e247f <unknown>
#6 0x5e9dfd9d9de3 <unknown>
#7 0x5e9dfd9af2dd <unknown>
#8 0x5e9dfd9b034e <unknown>
#9 0x5e9dfdc0f3e4 <unknown>
#10 0x5e9dfdc133d7 <unknown>
#11 0x5e9dfdc1db20 <unknown>
#12 0x5e9dfdc14023 <unknown>
#13 0x5e9dfdbe21aa <unknown>
#14 0x5e9dfdc386b8 <unknown>
#15 0x5e9dfdc38847 <unknown>
#16 0x5e9dfdc48243 <unknown>
#17 0x77b566335134 <unknown>

[2025-07-25T09:55:26.021+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flipkart_sentiment_pipeline_v2, task_id=scrape_task, run_id=manual__2025-07-25T09:54:15.883996+00:00, execution_date=20250725T095415, start_date=20250725T095425, end_date=20250725T095526
[2025-07-25T09:55:26.053+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task scrape_task (Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5e9dfdc4f4e3 <unknown>
#1 0x5e9dfd97ec76 <unknown>
#2 0x5e9dfd9a7d78 <unknown>
#3 0x5e9dfd9a4029 <unknown>
#4 0x5e9dfd9e2ccc <unknown>
#5 0x5e9dfd9e247f <unknown>
#6 0x5e9dfd9d9de3 <unknown>
#7 0x5e9dfd9af2dd <unknown>
#8 0x5e9dfd9b034e <unknown>
#9 0x5e9dfdc0f3e4 <unknown>
#10 0x5e9dfdc133d7 <unknown>
#11 0x5e9dfdc1db20 <unknown>
#12 0x5e9dfdc14023 <unknown>
#13 0x5e9dfdbe21aa <unknown>
#14 0x5e9dfdc386b8 <unknown>
#15 0x5e9dfdc38847 <unknown>
#16 0x5e9dfdc48243 <unknown>
#17 0x77b566335134 <unknown>
; 3589)
[2025-07-25T09:55:26.114+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-25T09:55:26.170+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T09:55:26.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
