[2025-07-28T21:30:28.816+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T21:30:29.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.create_reviewer_data_table manual__2025-07-28T21:30:19.755972+00:00 [queued]>
[2025-07-28T21:30:29.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.create_reviewer_data_table manual__2025-07-28T21:30:19.755972+00:00 [queued]>
[2025-07-28T21:30:29.775+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-28T21:30:29.993+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_reviewer_data_table> on 2025-07-28 21:30:19.755972+00:00
[2025-07-28T21:30:30.007+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=423) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T21:30:30.007+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_scraping_pipeline', 'create_reviewer_data_table', 'manual__2025-07-28T21:30:19.755972+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/parallel_pipeline_dag.py', '--cfg-path', '/tmp/tmp042m_v92']
[2025-07-28T21:30:30.008+0000] {standard_task_runner.py:64} INFO - Started process 432 to run task
[2025-07-28T21:30:30.009+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask create_reviewer_data_table
[2025-07-28T21:30:30.571+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T21:30:31.989+0000] {task_command.py:426} INFO - Running <TaskInstance: parallel_scraping_pipeline.create_reviewer_data_table manual__2025-07-28T21:30:19.755972+00:00 [running]> on host 88e3cb6438f4
[2025-07-28T21:30:35.021+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parallel_scraping_pipeline' AIRFLOW_CTX_TASK_ID='create_reviewer_data_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T21:30:19.755972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T21:30:19.755972+00:00'
[2025-07-28T21:30:35.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T21:30:35.026+0000] {sql.py:282} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS flipkart_reviewer_data (
            "Phone_Name" TEXT, 
            "Price" FLOAT(53), 
            "Review_ID" TEXT, 
            "Author" TEXT, 
            "Location" TEXT, 
            "Rating" BIGINT, 
            "Title" TEXT, 
            "Review" TEXT, 
            "Month" TEXT, 
            "Year" FLOAT(53)
        );
        
[2025-07-28T21:30:35.507+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-28T21:30:36.030+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-28T21:30:36.037+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T21:30:36.038+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 438, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 560, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-07-28T21:30:36.582+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parallel_scraping_pipeline, task_id=create_reviewer_data_table, run_id=manual__2025-07-28T21:30:19.755972+00:00, execution_date=20250728T213019, start_date=20250728T213029, end_date=20250728T213036
[2025-07-28T21:30:38.062+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task create_reviewer_data_table (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 432)
[2025-07-28T21:30:38.104+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-28T21:30:38.569+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-07-28T21:30:39.051+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T21:30:39.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
