[2025-07-29T07:05:12.346+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-29T07:05:13.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sequential_scraping_pipeline.create_reviewer_data_table_seq manual__2025-07-29T07:04:58.685924+00:00 [queued]>
[2025-07-29T07:05:13.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sequential_scraping_pipeline.create_reviewer_data_table_seq manual__2025-07-29T07:04:58.685924+00:00 [queued]>
[2025-07-29T07:05:13.671+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-29T07:05:14.239+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_reviewer_data_table_seq> on 2025-07-29 07:04:58.685924+00:00
[2025-07-29T07:05:14.257+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sequential_scraping_pipeline', 'create_reviewer_data_table_seq', 'manual__2025-07-29T07:04:58.685924+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/sequential_pipeline_dag.py', '--cfg-path', '/tmp/tmp1ubbhupy']
[2025-07-29T07:05:14.258+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=476) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-29T07:05:14.260+0000] {standard_task_runner.py:64} INFO - Started process 486 to run task
[2025-07-29T07:05:14.260+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask create_reviewer_data_table_seq
[2025-07-29T07:05:15.471+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-29T07:05:18.008+0000] {task_command.py:426} INFO - Running <TaskInstance: sequential_scraping_pipeline.create_reviewer_data_table_seq manual__2025-07-29T07:04:58.685924+00:00 [running]> on host 507e5441ba68
[2025-07-29T07:05:27.556+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sequential_scraping_pipeline' AIRFLOW_CTX_TASK_ID='create_reviewer_data_table_seq' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T07:04:58.685924+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-29T07:04:58.685924+00:00'
[2025-07-29T07:05:27.561+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-29T07:05:27.563+0000] {sql.py:282} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS flipkart_reviewer_data (
            "Phone_Name" TEXT, "Price" FLOAT(53), "Review_ID" TEXT,
            "Author" TEXT, "Location" TEXT, "Rating" BIGINT, "Title" TEXT,
            "Review" TEXT, "Month" TEXT, "Year" FLOAT(53)
        );
        
[2025-07-29T07:05:31.171+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-29T07:05:32.862+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-29T07:05:32.869+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-29T07:05:32.870+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 438, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 560, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-07-29T07:05:34.775+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sequential_scraping_pipeline, task_id=create_reviewer_data_table_seq, run_id=manual__2025-07-29T07:04:58.685924+00:00, execution_date=20250729T070458, start_date=20250729T070513, end_date=20250729T070534
[2025-07-29T07:05:35.336+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task create_reviewer_data_table_seq (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 486)
[2025-07-29T07:05:35.386+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-29T07:05:36.220+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
