[2025-07-29T11:49:36.514+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-29T11:49:39.142+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T11:47:54.549432+00:00 map_index=0 [queued]>
[2025-07-29T11:49:43.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T11:47:54.549432+00:00 map_index=0 [queued]>
[2025-07-29T11:49:43.201+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-29T11:49:47.219+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): scrape_task> on 2025-07-29 11:47:54.549432+00:00
[2025-07-29T11:49:47.290+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2932) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-29T11:49:47.294+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_scraping_pipeline', 'scrape_task', 'manual__2025-07-29T11:47:54.549432+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/parallel_pipeline_dag.py', '--cfg-path', '/tmp/tmplxkflv6n', '--map-index', '0']
[2025-07-29T11:49:47.300+0000] {standard_task_runner.py:64} INFO - Started process 2952 to run task
[2025-07-29T11:49:47.302+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask scrape_task
[2025-07-29T11:49:48.666+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-29T11:49:52.570+0000] {task_command.py:426} INFO - Running <TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T11:47:54.549432+00:00 map_index=0 [running]> on host dd044cea268d
[2025-07-29T11:50:08.711+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parallel_scraping_pipeline' AIRFLOW_CTX_TASK_ID='scrape_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T11:47:54.549432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-29T11:47:54.549432+00:00'
[2025-07-29T11:50:09.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-29T11:50:09.073+0000] {logging_mixin.py:188} INFO - Initializing Stealth WebDriver...
[2025-07-29T11:50:52.756+0000] {logging_mixin.py:188} INFO - Extracted - Phone: OPPO K13 5G with 7000mAh and 80W SUPERVOOC Charger In-The-Box (Icy Purple, 128 GB)  (8 GB RAM), Price: â‚¹17,999
[2025-07-29T11:50:58.732+0000] {logging_mixin.py:188} INFO - Scraping Page 1 for OPPO K13 5G with 7000mAh and 80W SUPERVOOC Charger In-The-Box (Icy Purple, 128 GB)  (8 GB RAM)...
[2025-07-29T11:51:04.455+0000] {logging_mixin.py:188} INFO - Scraping Page 2 for OPPO K13 5G with 7000mAh and 80W SUPERVOOC Charger In-The-Box (Icy Purple, 128 GB)  (8 GB RAM)...
[2025-07-29T11:51:10.146+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-29T11:51:11.157+0000] {process_utils.py:132} INFO - Sending 15 to group 2952. PIDs of all processes in the group: [3115, 3130, 3153, 3154, 3187, 3194, 3235, 3250, 3185, 2952]
[2025-07-29T11:51:11.430+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2952
[2025-07-29T11:51:11.764+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-29T11:51:12.391+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /session/f27b45af59e713ee574861e4981d1969
[2025-07-29T11:51:12.720+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72136c9d3170>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f27b45af59e713ee574861e4981d1969
[2025-07-29T11:51:13.000+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72136c9d3230>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f27b45af59e713ee574861e4981d1969
[2025-07-29T11:51:13.138+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3194, status='terminated', started='11:50:11') (3194) terminated with exit code None
[2025-07-29T11:51:13.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-29T11:51:13.546+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3130, status='terminated', started='11:50:10') (3130) terminated with exit code None
[2025-07-29T11:51:13.842+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3185, status='terminated', started='11:50:11') (3185) terminated with exit code None
[2025-07-29T11:51:13.958+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3187, status='terminated', started='11:50:11') (3187) terminated with exit code None
[2025-07-29T11:51:14.010+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3250, status='terminated', started='11:50:14') (3250) terminated with exit code None
[2025-07-29T11:51:14.052+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3153, status='terminated', started='11:50:10') (3153) terminated with exit code None
[2025-07-29T11:51:14.159+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3115, status='terminated', started='11:50:10') (3115) terminated with exit code None
[2025-07-29T11:51:14.161+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3154, status='terminated', started='11:50:10') (3154) terminated with exit code None
[2025-07-29T11:51:15.370+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3235, status='terminated', started='11:50:13') (3235) terminated with exit code None
[2025-07-29T11:51:15.794+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parallel_pipeline_dag.py", line 46, in scrape_task
    return scrape_reviews_for_url(phone_url=url, output_folder=RAW_DATA_FOLDER)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraper_module.py", line 168, in scrape_reviews_for_url
    WebDriverWait(driver, 15).until(EC.staleness_of(first_review_el))
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 129, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py", line 656, in _predicate
    element.is_enabled()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 258, in is_enabled
    return self._execute(Command.IS_ELEMENT_ENABLED)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 573, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 451, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 135, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 182, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-29T11:51:16.279+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parallel_scraping_pipeline, task_id=scrape_task, run_id=manual__2025-07-29T11:47:54.549432+00:00, map_index=0, execution_date=20250729T114754, start_date=20250729T114939, end_date=20250729T115116
[2025-07-29T11:51:17.628+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2952, status='terminated', exitcode=2, started='11:49:47') (2952) terminated with exit code 2
[2025-07-29T11:51:17.642+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 143
