[2025-07-25T10:15:41.531+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T10:15:41.577+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T10:15:32.009633+00:00 [queued]>
[2025-07-25T10:15:41.591+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T10:15:32.009633+00:00 [queued]>
[2025-07-25T10:15:41.592+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-25T10:15:41.612+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): scrape_task> on 2025-07-25 10:15:32.009633+00:00
[2025-07-25T10:15:41.633+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-25T10:15:41.637+0000] {standard_task_runner.py:64} INFO - Started process 104 to run task
[2025-07-25T10:15:41.636+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flipkart_sentiment_pipeline_v2', 'scrape_task', 'manual__2025-07-25T10:15:32.009633+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sentiment_pipeline_dag.py', '--cfg-path', '/tmp/tmpkohuj2rt']
[2025-07-25T10:15:41.639+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask scrape_task
[2025-07-25T10:15:41.660+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-07-25T10:15:41.761+0000] {task_command.py:426} INFO - Running <TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T10:15:32.009633+00:00 [running]> on host fb07c225d43f
[2025-07-25T10:15:41.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flipkart_sentiment_pipeline_v2' AIRFLOW_CTX_TASK_ID='scrape_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T10:15:32.009633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T10:15:32.009633+00:00'
[2025-07-25T10:15:41.916+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T10:15:41.918+0000] {logging_mixin.py:188} INFO - Starting scrape for URL: https://www.flipkart.com/apple-iphone-15-black-128-gb/p/itme5f540d559560
[2025-07-25T10:15:41.919+0000] {logging_mixin.py:188} INFO - Initializing WebDriver...
[2025-07-25T10:15:41.921+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-07-25T10:15:41.965+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T10:15:42.362+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-07-25T10:15:42.750+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-07-25T10:16:29.566+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T10:16:30.450+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T10:16:30.801+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-07-25T10:16:31.514+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T10:16:31.516+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sentiment_pipeline_dag.py", line 39, in scrape_task
    file_path = scrape_reviews_for_url(phone_url=url, output_folder=RAW_DATA_FOLDER)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraper_module.py", line 55, in scrape_reviews_for_url
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 261, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 362, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x64b9d40db4e3 <unknown>
#1 0x64b9d3e0ac76 <unknown>
#2 0x64b9d3e33d78 <unknown>
#3 0x64b9d3e30029 <unknown>
#4 0x64b9d3e6eccc <unknown>
#5 0x64b9d3e6e47f <unknown>
#6 0x64b9d3e65de3 <unknown>
#7 0x64b9d3e3b2dd <unknown>
#8 0x64b9d3e3c34e <unknown>
#9 0x64b9d409b3e4 <unknown>
#10 0x64b9d409f3d7 <unknown>
#11 0x64b9d40a9b20 <unknown>
#12 0x64b9d40a0023 <unknown>
#13 0x64b9d406e1aa <unknown>
#14 0x64b9d40c46b8 <unknown>
#15 0x64b9d40c4847 <unknown>
#16 0x64b9d40d4243 <unknown>
#17 0x7822cdd04134 <unknown>

[2025-07-25T10:16:31.560+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flipkart_sentiment_pipeline_v2, task_id=scrape_task, run_id=manual__2025-07-25T10:15:32.009633+00:00, execution_date=20250725T101532, start_date=20250725T101541, end_date=20250725T101631
[2025-07-25T10:16:31.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task scrape_task (Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x64b9d40db4e3 <unknown>
#1 0x64b9d3e0ac76 <unknown>
#2 0x64b9d3e33d78 <unknown>
#3 0x64b9d3e30029 <unknown>
#4 0x64b9d3e6eccc <unknown>
#5 0x64b9d3e6e47f <unknown>
#6 0x64b9d3e65de3 <unknown>
#7 0x64b9d3e3b2dd <unknown>
#8 0x64b9d3e3c34e <unknown>
#9 0x64b9d409b3e4 <unknown>
#10 0x64b9d409f3d7 <unknown>
#11 0x64b9d40a9b20 <unknown>
#12 0x64b9d40a0023 <unknown>
#13 0x64b9d406e1aa <unknown>
#14 0x64b9d40c46b8 <unknown>
#15 0x64b9d40c4847 <unknown>
#16 0x64b9d40d4243 <unknown>
#17 0x7822cdd04134 <unknown>
; 104)
[2025-07-25T10:16:31.654+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-25T10:16:31.726+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T10:16:31.732+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
