[2025-07-25T08:06:58.991+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T08:06:59.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T08:06:49.366722+00:00 [queued]>
[2025-07-25T08:06:59.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T08:06:49.366722+00:00 [queued]>
[2025-07-25T08:06:59.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-25T08:06:59.151+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): scrape_task> on 2025-07-25 08:06:49.366722+00:00
[2025-07-25T08:06:59.180+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=494) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-25T08:06:59.184+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flipkart_sentiment_pipeline_v2', 'scrape_task', 'manual__2025-07-25T08:06:49.366722+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sentiment_pipeline_dag.py', '--cfg-path', '/tmp/tmpmuaif7oi']
[2025-07-25T08:06:59.186+0000] {standard_task_runner.py:64} INFO - Started process 504 to run task
[2025-07-25T08:06:59.186+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask scrape_task
[2025-07-25T08:06:59.223+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-07-25T08:06:59.358+0000] {task_command.py:426} INFO - Running <TaskInstance: flipkart_sentiment_pipeline_v2.scrape_task manual__2025-07-25T08:06:49.366722+00:00 [running]> on host 9435d83f948a
[2025-07-25T08:06:59.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flipkart_sentiment_pipeline_v2' AIRFLOW_CTX_TASK_ID='scrape_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T08:06:49.366722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T08:06:49.366722+00:00'
[2025-07-25T08:06:59.603+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T08:06:59.605+0000] {logging_mixin.py:188} INFO - Starting scrape for URL: https://www.flipkart.com/apple-iphone-15-black-128-gb/p/itme5f540d559560
[2025-07-25T08:06:59.606+0000] {logging_mixin.py:188} INFO - Initializing WebDriver...
[2025-07-25T08:06:59.608+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-07-25T08:06:59.681+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T08:07:00.396+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-07-25T08:07:00.740+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-07-25T08:08:09.818+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T08:08:10.807+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-25T08:08:11.253+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-07-25T08:08:12.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T08:08:12.518+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sentiment_pipeline_dag.py", line 39, in scrape_task
    file_path = scrape_reviews_for_url(phone_url=url, output_folder=RAW_DATA_FOLDER)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraper_module.py", line 55, in scrape_reviews_for_url
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 261, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 362, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x61b7497674e3 <unknown>
#1 0x61b749496c76 <unknown>
#2 0x61b7494bfd78 <unknown>
#3 0x61b7494bc029 <unknown>
#4 0x61b7494faccc <unknown>
#5 0x61b7494fa47f <unknown>
#6 0x61b7494f1de3 <unknown>
#7 0x61b7494c72dd <unknown>
#8 0x61b7494c834e <unknown>
#9 0x61b7497273e4 <unknown>
#10 0x61b74972b3d7 <unknown>
#11 0x61b749735b20 <unknown>
#12 0x61b74972c023 <unknown>
#13 0x61b7496fa1aa <unknown>
#14 0x61b7497506b8 <unknown>
#15 0x61b749750847 <unknown>
#16 0x61b749760243 <unknown>
#17 0x7802e219d134 <unknown>

[2025-07-25T08:08:12.572+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flipkart_sentiment_pipeline_v2, task_id=scrape_task, run_id=manual__2025-07-25T08:06:49.366722+00:00, execution_date=20250725T080649, start_date=20250725T080659, end_date=20250725T080812
[2025-07-25T08:08:12.619+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task scrape_task (Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x61b7497674e3 <unknown>
#1 0x61b749496c76 <unknown>
#2 0x61b7494bfd78 <unknown>
#3 0x61b7494bc029 <unknown>
#4 0x61b7494faccc <unknown>
#5 0x61b7494fa47f <unknown>
#6 0x61b7494f1de3 <unknown>
#7 0x61b7494c72dd <unknown>
#8 0x61b7494c834e <unknown>
#9 0x61b7497273e4 <unknown>
#10 0x61b74972b3d7 <unknown>
#11 0x61b749735b20 <unknown>
#12 0x61b74972c023 <unknown>
#13 0x61b7496fa1aa <unknown>
#14 0x61b7497506b8 <unknown>
#15 0x61b749750847 <unknown>
#16 0x61b749760243 <unknown>
#17 0x7802e219d134 <unknown>
; 504)
[2025-07-25T08:08:12.672+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-25T08:08:12.721+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T08:08:12.728+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
