[2025-07-29T11:49:36.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-29T11:49:38.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T11:47:54.549432+00:00 map_index=1 [queued]>
[2025-07-29T11:49:42.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T11:47:54.549432+00:00 map_index=1 [queued]>
[2025-07-29T11:49:42.517+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-29T11:49:46.685+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): scrape_task> on 2025-07-29 11:47:54.549432+00:00
[2025-07-29T11:49:46.756+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2933) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-29T11:49:46.756+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_scraping_pipeline', 'scrape_task', 'manual__2025-07-29T11:47:54.549432+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/parallel_pipeline_dag.py', '--cfg-path', '/tmp/tmpngpg5bv0', '--map-index', '1']
[2025-07-29T11:49:46.763+0000] {standard_task_runner.py:64} INFO - Started process 2951 to run task
[2025-07-29T11:49:46.768+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask scrape_task
[2025-07-29T11:49:48.287+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-29T11:49:52.179+0000] {task_command.py:426} INFO - Running <TaskInstance: parallel_scraping_pipeline.scrape_task manual__2025-07-29T11:47:54.549432+00:00 map_index=1 [running]> on host dd044cea268d
[2025-07-29T11:50:06.788+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parallel_scraping_pipeline' AIRFLOW_CTX_TASK_ID='scrape_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T11:47:54.549432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-29T11:47:54.549432+00:00'
[2025-07-29T11:50:06.795+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-29T11:50:06.799+0000] {logging_mixin.py:188} INFO - Initializing Stealth WebDriver...
[2025-07-29T11:50:48.591+0000] {logging_mixin.py:188} INFO - Extracted - Phone: Apple iPhone SE (Red, 64 GB) (Includes EarPods, Power Adapter), Price: â‚¹39,900
[2025-07-29T11:50:55.734+0000] {logging_mixin.py:188} INFO - Scraping Page 1 for Apple iPhone SE (Red, 64 GB) (Includes EarPods, Power Adapter)...
[2025-07-29T11:51:05.183+0000] {logging_mixin.py:188} INFO - Scraping Page 2 for Apple iPhone SE (Red, 64 GB) (Includes EarPods, Power Adapter)...
[2025-07-29T11:51:10.079+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-29T11:51:11.095+0000] {process_utils.py:132} INFO - Sending 15 to group 2951. PIDs of all processes in the group: [2994, 3000, 3021, 3022, 3048, 3049, 3122, 3155, 3046, 2951]
[2025-07-29T11:51:11.454+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2951
[2025-07-29T11:51:11.612+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-29T11:51:12.293+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /session/b85cc7ff06768b40e71d00863f1f8d3f
[2025-07-29T11:51:12.457+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72136c9d7260>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b85cc7ff06768b40e71d00863f1f8d3f
[2025-07-29T11:51:12.689+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72136c9d7590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b85cc7ff06768b40e71d00863f1f8d3f
[2025-07-29T11:51:12.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-29T11:51:13.063+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2994, status='terminated', started='11:50:06') (2994) terminated with exit code None
[2025-07-29T11:51:13.722+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3046, status='terminated', started='11:50:08') (3046) terminated with exit code None
[2025-07-29T11:51:13.822+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3049, status='terminated', started='11:50:08') (3049) terminated with exit code None
[2025-07-29T11:51:13.914+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3155, status='terminated', started='11:50:11') (3155) terminated with exit code None
[2025-07-29T11:51:14.810+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3048, status='terminated', started='11:50:08') (3048) terminated with exit code None
[2025-07-29T11:51:14.814+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3000, status='terminated', started='11:50:07') (3000) terminated with exit code None
[2025-07-29T11:51:14.831+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3022, status='terminated', started='11:50:07') (3022) terminated with exit code None
[2025-07-29T11:51:14.845+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3122, status='terminated', started='11:50:10') (3122) terminated with exit code None
[2025-07-29T11:51:14.870+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3021, status='terminated', started='11:50:07') (3021) terminated with exit code None
[2025-07-29T11:51:14.919+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parallel_pipeline_dag.py", line 46, in scrape_task
    return scrape_reviews_for_url(phone_url=url, output_folder=RAW_DATA_FOLDER)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraper_module.py", line 165, in scrape_reviews_for_url
    next_button.click()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 120, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 573, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 451, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-29T11:51:15.467+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parallel_scraping_pipeline, task_id=scrape_task, run_id=manual__2025-07-29T11:47:54.549432+00:00, map_index=1, execution_date=20250729T114754, start_date=20250729T114938, end_date=20250729T115115
[2025-07-29T11:51:17.278+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2951, status='terminated', exitcode=2, started='11:49:46') (2951) terminated with exit code 2
[2025-07-29T11:51:17.286+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 143
[2025-07-29T11:51:17.310+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py:39 SAWarning: transaction already deassociated from connection
[2025-07-29T11:51:17.319+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
